version: "3.5"
services:
  postgres:
    container_name: liblesson_postgres
    image: postgres
    networks:
      liblesson:
        ipv4_address: "172.49.0.2"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  web:
    container_name: liblesson_web
    build: .
    networks:
      liblesson:
        ipv4_address: "172.49.0.3"
    depends_on:
      - postgres
    tty: true
    command: bash -c "python manage.py makemigrations core & python manage.py migrate core & python manage.py makemigrations & python manage.py migrate
      & python manage.py collectstatic --noinput
      & gunicorn --workers=8 -c gunicorn.py liblesson.wsgi --timeout 600"
    volumes:
      - .:/code
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: liblesson_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./media/:/code/media
      - ./static/:/code/static
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      liblesson:
        ipv4_address: "172.49.0.4"

networks:
  liblesson:
    driver: bridge
    ipam:
      config:
        - subnet: "172.49.0.0/16"