version: "3.5"
services:
  postgres:
    container_name: liblesson_postgres
    image: postgres
    ports:
    - "5437:5432"
    networks:
      liblesson:
        ipv4_address: "172.49.0.2"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  web:
    container_name: liblesson_web
    build: .
    ports:
    - "8889:8889"
    networks:
      liblesson:
        ipv4_address: "172.49.0.3"
    depends_on:
      - postgres
    tty: true
    command: bash -c "python manage.py makemigrations & python manage.py makemigrations core  & python manage.py migrate & python manage.py migrate core & python manage.py runserver 0.0.0.0:8889"
    volumes:
      - .:/code
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

networks:
  liblesson:
    driver: bridge
    ipam:
      config:
        - subnet: "172.49.0.0/16"